import "./globals.css";
import NavBar from "./_Components/NavBar/NavBar";
import SideBar from "./_Components/SideBar/SideBar";
import getAllCategories from "../APIs/GetAllcategories";
import GetAllBrands from "../APIs/GetAllBrands";
import { Toaster } from "@/components/ui/sonner";
import Providers from "_/Providers";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const Categories = await getAllCategories();
  const Brands = await GetAllBrands();
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <Providers>
          <SidebarProvider defaultOpen={defaultOpen} style={{
            "--sidebar-width": "15rem",
            "--sidebar-width-mobile": "20rem",
          }} className=' h-screen'>
            <SideBar Categories={Categories} Brands={Brands} />
            <main className="flex flex-col">
              <NavBar />
              <section className="p-14  bg-amber-200">
                {children}
              </section>
            </main>
            <Toaster />
          </SidebarProvider>
        </Providers>
      </body>
    </html >
  );
}
